### ISSUE TITLE
package flag: unrecognized import path "flag"

### ISSUE THREAD

**Issue by zhenglu1989** [rakyll/boom#101]
I'm trying to install , but running go get github.com/rakyll/boom returns：
package flag: unrecognized import path "flag"
package fmt: unrecognized import path "fmt"
package crypto/tls: unrecognized import path "crypto/tls"
package io: unrecognized import path "io"
package math: unrecognized import path "math"
package runtime: unrecognized import path "runtime"
package strconv: unrecognized import path "strconv"
package strings: unrecognized import path "strings"
package sync/atomic: unrecognized import path "sync/atomic"
package syscall: unrecognized import path "syscall"
package time: unrecognized import path "time"
package unsafe: unrecognized import path "unsafe"
package io/ioutil: unrecognized import path "io/ioutil"
package net/http: unrecognized import path "net/http"
package net/url: unrecognized import path "net/url"
package os: unrecognized import path "os"
package os/signal: unrecognized import path "os/signal"
package sort: unrecognized import path "sort"
package sync: unrecognized import path "sync"
package regexp: unrecognized import path "regexp"

**Comment by missedone** [comment]
which golang version you're using, could you check your GOROOT, GOPATH to see if golang correctly installed/configured?

**Comment by rakyll** [comment]
Could you paste the output of the following?

```
$ go env
```

**Comment by zhenglu1989** [comment]
when i excute go env ，returns：
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zhenglu/Documents/go-code"
GORACE=""
GOROOT="/usr/local/Cellar/go"
GOTOOLDIR="/usr/local/Cellar/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by rakyll** [comment]
Are you installing go from homebrew? Homebrew go formula is poorly maintained and is at go1.3.3. Use the official installer at https://golang.org/dl/.

**Comment by zhenglu1989** [comment]
thank you very much
