### ISSUE TITLE
Renaming the project

### ISSUE THREAD

**Issue by tarekziade** [rakyll/boom#130]
Hello!

I was wondering if you would not mind renaming your project, I think there could be some confusion at this point because both projects have slightly different options now.

**Comment by rakyll** [comment]
I have been thinking about it as well but it seems to be pretty hard at this moment.

This tool is widely used and renaming the binary will break a lot of users. It is such a shame that boom was supposed to be a reference program only but it is also actively used.

**Comment by tarekziade** [comment]
I am wondering why you kept my project name for your fork though. You made the mistake to use my project name to publish your fork, you should go through the pain of renaming it - not me...

By refusing to rename it, you are basically hijacking it this point, what makes me cringe the most is your "copyright google" in there. 

Not cool, this is not how open source works.

**Comment by rakyll** [comment]
I am sorry. I am not happy with the current name neither trying to keep it. The situation is renaming things just won't take the history back, such as it won't change the existing references to this project or the articles on the Internet. The confusion will keep being there. This is what I want to address first.

It is not cool that you are attacking me by calling it a "hijack". When I published this tool, I let you know and the README gave credit to your project credit from the very beginning. https://twitter.com/rakyll/status/419939763404435456

It is probably my fault I haven't renamed it when it attracted people.

I am very disappointed in your response above and escalation of this issue on Twitter. You are attacking me personally even though I showed good intent and I am not happy with the current situation either.

**Comment by rakyll** [comment]
> I am wondering why you kept my project name for your fork though

This repo is not derived from your work. It is a port not a fork.

**Comment by tarekziade** [comment]
> The confusion will keep being there

You have created the confusion.

> It is not cool that you are attacking me by calling it a "hijack"

If you keep the same name it is a hijack. Nothing else.

> I let you know and the README gave credit to your project credit from the very beginning

Yes, and I was very happy that your forked the project. But I did not know you were going to publish it under the exact same name. **EVEN THE COMMAND LINE IS THE SAME NAME**

> I am very disappointed in your response above and escalation of this issue on Twitter. You are attacking me personally even though I showed good intent and I am not happy with the current situation either.

It's not personal, it's just the consequence of your unwillingness to rename the project, which demonstrates the fact that you made the decision to own my project name when I am telling you I don't want you to do it. 

I was pretty sure you have good intents, until you said "no" to the renaming. If you want to do the right thing, you need to rename it. If you don't rename it, you being the bad guy, not me.

**Comment by tarekziade** [comment]
> This repo is not derived from your work. It is a port not a fork.

It's not a port. You added different options. It's a different project now, and you are using my project name. Which is the only issue here. It's called a hijack.

**Comment by rakyll** [comment]
> But I did not know you were going to publish it under the exact same name. EVEN THE COMMAND LINE IS THE SAME NAME

It was already PUBLIC(*) when I wrote it to you. I haven't "published" it. Someone shared it on Reddit and that's how it got popular. I am not maintaining this project since then.

Whatever you are complaining about is not the actual story and I haven't said "no". I haven't closed the issue. Read my comments above and see the occurrence of "no"s. I explained the case and the problem because of the name collision.

This project is not a fork of your project. It is not derived from your work. You are trying to claim copyright on interfaces.

* Because yelling at people makes your argument stronger.

**Comment by rakyll** [comment]
If it is not clear from my initial response, I am trying to understand the impact on the existing users.

non-breaking:
* go gets will be redirected
* the repo will be redirected

breaking:
* all references to `boom` will not work
* the binary name will change
* docker hub image needs to be updated

I will update the list as more significant items come to my mind.

**Comment by tarekziade** [comment]
> I haven't said "no"

Ah ok, sorry I have interpreted this as a no: "it seems to be pretty hard at this moment. This tool is widely used and renaming the binary will break a lot of users"

> Whatever you are complaining about is not the actual story

why are you trying to argue when the thing is super simple ? you are using 'boom' as a name for your tool. 

> You are trying to claim copyright on interfaces.

Interfaces ?  I am not sure what you are talking about. I am not claiming any specific stuff about 
whatever you do in your project. My claim is simple, I am asking you to rename it.

If you are willing to do it, e.g re-release it under a new name, then the argument is over. 

I apologize if you feel that I am attacking you, or if I am overreacting. But try to think for a second from my point of view: when I asked you to rename it, your answer did not sound at all like a yes to me and my reaction was to think that you are not going to do it. 

If we can work this out then, cool.

**Comment by rakyll** [comment]
> why are you trying to argue when the thing is super simple ? you are using 'boom' as a name for your tool.

I am not arguing. You are arguing with me and escalating things to public even though I want to fix this problem. Please stop blaming me for your poor communication skills.

> Interfaces ? I am not sure what you are talking about.

"EVEN THE COMMAND LINE IS THE SAME NAME" I am trying to understand what you mean here.

I kindly request you to apologize me in public for your misunderstanding and unnecessary reaction.

I will rename the project right after getting done with the list at https://github.com/rakyll/boom/issues/130#issuecomment-244308044.

**Comment by tarekziade** [comment]
> Please stop blaming me for your poor communication skills.

I don't think you're better than me in communication skills. We would not be doing all this argument otherwise. The project would already be renamed.

> "EVEN THE COMMAND LINE IS THE SAME NAME" I am trying to understand what you mean here.

To use the tool, the command line to call in your shell is "boom", e.g.

$ boom <options>

which means that if people install mine and yours, I am not even sure which one prevails 

> I kindly request you to apologize me in public for your misunderstanding and unnecessary reaction.

I did, before I even saw this request :)

**Comment by mdakin** [comment]
How about forking current boom project(go version), renaming it to something like "gboom" or "boomg" and keeping the existing one with a deprecation / forward notice? 
So nothing will be broken for anyone, go version will have a new name.

**Comment by rakyll** [comment]
> re: gboom

g'ing things kinda resembles Google stuff. Given copyright is also shared with Google. I think we should never g name. goboom might be ok but very mouthful.

I have another suggestion at https://github.com/rakyll/boom/pull/131. Not sure that it will be fine.

**Comment by rakyll** [comment]
Ah, ab+ is an invalid import path to begin with. Not going to work. Suggestions are welcome.

**Comment by mdakin** [comment]
boomg was short for (bo-OMG), I meant 'g' as abbreviation to go, not google, but fair enough, maybe a 'boom' like name is not a good idea anymore.

**Comment by rakyll** [comment]
> How about forking current boom project(go version), renaming it to something like "gboom" or "boomg" and keeping the existing one with a deprecation / forward notice? 

As long as we don't change the import path, people won't move. I am not sure what's the percentage of people who are visiting the project README. They see the go get github.com/rakyll/boom on the wild Web and copy paste into their terminal.

These cases are what I wanted to investigate before jumping on a solution that is not going to fix anything.

**Comment by mdakin** [comment]
> As long as we don't change the import path, people won't move. I am not sure what's the percentage of people who are visiting the project README. They see the go get github.com/rakyll/boom on the wild Web and copy paste into their terminal.

You can put the deprecation notice into code. Something like:

$boom 
*** boom is deprecated, please use <name> from <site> **
...usual boom output...

**Comment by rakyll** [comment]
> You can put the deprecation notice into code. Something like:

SGTM

I will also migrate the issues to the new repo.

> maybe a 'boom' like name is not a good idea anymore.

I'd prefer something distinct and short. I was thinking about a word around salutation. "hey" could be nice.

**Comment by rakyll** [comment]
The project lives under https://github.com/rakyll/hey now.
