### ISSUE TITLE
Doesn't work in Windows

### ISSUE THREAD

**Issue by ianaz** [rakyll/boom#54]
I can't launch it on windows. Installed using your instructions:

C:\Users\rai>go get github.com/rakyll/boom

C:\Users\rai>boom -n 1000 -c 100 https://google.com

"boom" command not found...etc

go1.3.3 windows/amd64
Windows 7

**Comment by insionng** [comment]
go get github.com/rakyll/boom
go install github.com/rakyll/boom
boom -n 1000 -c 100 http://www.baidu.com

**Comment by rakyll** [comment]
Please, reopen this issue if you need any further help.
