### ISSUE TITLE
unknown http.Transport field 'TLSHandshakeTimeout' in struct literal

### ISSUE THREAD

**Issue by bengadbois** [rakyll/boom#55]
Ran "go get github.com/rakyll/boom" and got the following:

github.com/rakyll/boom/boomer
boomer/run.go:55: unknown http.Transport field 'TLSHandshakeTimeout' in struct literal

go version go1.2.1 linux/amd64

**Comment by tmadge** [comment]
Get the latest version of Go.

I had the same problem with go1.2.2... just upgraded to go1.4.1 and it works.

**Comment by eignerchris** [comment]
I was having this issue, upgraded to 1.4.2 and now get the following error when trying to `go get`

````
go/src/github.com/rakyll/boom/boomer/boomer.go:24: import go/pkg/darwin_amd64/github.com/rakyll/pb.a: object is [darwin amd64 go1.1.2 X:none] expected [darwin amd64 go1.4.2 X:precisestack]
````

**Comment by RyanHartje** [comment]
bump, I get the same thing with the apt version of golang.
