### ISSUE TITLE
-bash: boom: command not found?

### ISSUE THREAD

**Issue by Dreampie** [rakyll/boom#63]
go get github.com/rakyll/boom
package crypto/tls: unrecognized import path "crypto/tls"
package errors: unrecognized import path "errors"
package flag: unrecognized import path "flag"
package fmt: unrecognized import path "fmt"
package io: unrecognized import path "io"
package math: unrecognized import path "math"
package runtime: unrecognized import path "runtime"
package strconv: unrecognized import path "strconv"
package strings: unrecognized import path "strings"
package sync/atomic: unrecognized import path "sync/atomic"
package syscall: unrecognized import path "syscall"
package time: unrecognized import path "time"
package unsafe: unrecognized import path "unsafe"
package net: unrecognized import path "net"
package net/http: unrecognized import path "net/http"
package net/url: unrecognized import path "net/url"
package sort: unrecognized import path "sort"
package sync: unrecognized import path "sync"
package os: unrecognized import path "os"
package regexp: unrecognized import path "regexp"

boom
-bash: boom: command not found

**Comment by odeke-em** [comment]
Please make sure you have set your $GOPATH or $GOROOT in your environment or .bashrc or .bash_profile file depending on what OS you are on.
If you haven't done so, here is a sample piece of code to do it in your bash shell on Linux:
```shell
$ cat << ! >> ~/.bashrc
> export GOPATH="\$HOME/gopath"
> export PATH="\$GOPATH:\$GOPATH/bin:\$PATH"
> !
```
Otherwise you can read more on how to properly install Go here https://golang.org/doc/install
