### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Natim** [rakyll/boom#67]
```
$ go get github.com/rakyll/boom
# github.com/rakyll/boom/boomer
../../../.go-packages/src/github.com/rakyll/boom/boomer/run.go:55:3: error: unknown field ‘TLSHandshakeTimeout’ in ‘http.Transport’
   TLSHandshakeTimeout: time.Duration(b.Timeout) * time.Millisecond,
   ^
../../../.go-packages/src/github.com/rakyll/boom/boomer/run.go:58:36: error: incompatible type for field 1 in struct construction (type has no methods)
  client := &http.Client{Transport: tr}
                                    ^
```

**Comment by Natim** [comment]
$ go version
    go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64

**Comment by odeke-em** [comment]
Please make sure you have set your $GOPATH (as raised by this error) in your environment or .bashrc or .bash_profile file depending on what OS you are on.
If you haven't done so, here is a sample piece of code to do it in your bash shell on Linux:
```shell
$ cat << ! >> ~/.bashrc
> export GOPATH="\$HOME/gopath"
> export PATH="\$GOPATH:\$GOPATH/bin:\$PATH"
> !
```
Otherwise you can read more on how to properly install Go here https://golang.org/doc/install

**Comment by Natim** [comment]
I did it but I still have the same error.

**Comment by odeke-em** [comment]
And you remembered to reload the settings? If not you can do so by
```shell
$ source ~/.bashrc
```
Or by opening a new shell.

**Comment by Natim** [comment]
Yes of course :)

**Comment by Natim** [comment]
```
cat << ! > home.go
import "fmt"

func main() {
    fmt.Printf("hello, world\n")
}
!
~/go$ go run home.go 
hello, world
```

**Comment by Natim** [comment]
Ok so I remove all the go version installed gccgo, /usr/local/go, ~/go and I reinstalled ``golang-go``

Now I run ``go version go1.2.1 linux/amd64``

And when trying to run ``go get github.com/rakyll/boom``

I've got this error:

```
# github.com/rakyll/boom/boomer
../.go-packages/src/github.com/rakyll/boom/boomer/run.go:55: unknown http.Transport field 'TLSHandshakeTimeout' in struct literal
```

**Comment by Natim** [comment]
I am now trying to use ``ppa:evarlast/golang1.4`` in order to get ``go version go.1.4.2``

**Comment by Natim** [comment]
So with golang 1.4.1 it finally worked. Ubuntu golang version is outdated.
