### ISSUE TITLE
[This is not issue..] hi, i branch boom with another option, another ouput

### ISSUE THREAD

**Issue by heshed** [rakyll/boom#75]
Thank you for this great boom~
I'm newbie in golang, and English
I made just for fun and learning golang

see https://github.com/heshed/boom

- delete csv output
- show option values
- show stat per second
- add -i input file (required... some stupid feature.. want to solve it)
- read line and append URL at GET method
- change output format
- change histogram scale
- change stats : second to millisecond

**Comment by rakyll** [comment]
Closing this non-issue.
