### ISSUE TITLE
Auth should allow more characters in the username

### ISSUE THREAD

**Issue by gjesse** [rakyll/boom#85]
I have an auth token that contains a + symbol, and I ended up having to specify the auth header directly in order to use boom. Seems like it's locked down a bit too much.

Also, the error "Could not parse provided input" is pretty unhelpful as far as understanding what the problem is.

**Comment by gsquire** [comment]
@gjesse I thought I could take a shot at this issue. I tested myself with a small server that accepts basic authentication. If you want to see if it solves your problem, I would appreciate it!

**Comment by rakyll** [comment]
Please reopen the issue if https://github.com/rakyll/boom/pull/96 is not sufficient.
