### ISSUE TITLE
Please clarify: response time histogram with response time [zero requests]

### ISSUE THREAD

**Issue by modestkdr** [rakyll/boom#92]
As indicated in the screenshot below, some of the response times have a zero in square brackets. 
How can there be a response time with zero requests? please clarify.

![screen shot 2015-11-11 at 11 52 28 am](https://cloud.githubusercontent.com/assets/915560/11097020/ff0f9fd6-886a-11e5-9c58-4a29afec290a.png)

**Comment by mat** [comment]
These response times form equally sized *ranges* with the numbers from adjacent lines. So the first `[0]` means there is not even a single request that took between 9.120 and 12.188. However there is a single request that took more than 30.596 but at most 33.664 etc.

**Comment by modestkdr** [comment]
Thank you.
