### ISSUE TITLE
boom degrade benchmark performance due to non-reused connections

### ISSUE THREAD

**Issue by yichengq** [rakyll/boom#93]
I write a simple http service:
```
package main

import "net/http"

type handler struct{}

func (h *handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
}

func main() {
	http.ListenAndServe(":4001", &handler{})
}
```

The performance before https://github.com/rakyll/boom/commit/84d1d3814b5c5bfe3089071a8e1ec6a04701a6d2 is 38000req/s, after it the result is 28000req/s. This change breaks the feature of boom I believe.

After digging it more, the root cause is that boom doesn't reuse connections after this commit. The default setting of transport is to maintain at most 2 idle connections. If all clients, e.g. 100, share the same transport, they need to keep closing and creating new connections then. This slows down the benchmark process. A possible fix is to set higher idle connections number for the shared transport.

from https://github.com/rakyll/boom/pull/70#issuecomment-156252601
/cc @brodock

**Comment by rakyll** [comment]
Rather than reverting the change, we need a good setting for `MaxIdleConnsPerHost`. I can set it to 2*c and provide an option to override.

**Comment by rakyll** [comment]
I reverted the change. Expanding the pool size may not be enough. There is more synchronization going on with a global client, bringing the old model back.
